### PR TITLE
Fix incorrect mount point for openlane scripts.

### PR DESCRIPTION
**Pull request by mguthaus**
The mpw-3a docker image has a pre-installed copy of all the openlane scripts in /openlane. The caravel Makefile is supposed to mount the copy from $OPENLANE_ROOT in /openLANE_flow (this is with the mpw-3a caravel tag):
```
                docker run -it -v $(OPENLANE_ROOT):/openLANE_flow \
                -v $(PDK_ROOT):$(PDK_ROOT) \
                -v $(PWD)/..:/project \
                -v $(CARAVEL_ROOT):$(CARAVEL_ROOT) \
                -e PDK_ROOT=$(PDK_ROOT) \
                -e CARAVEL_ROOT=$(CARAVEL_ROOT) \
                -u $(shell id -u $(USER)):$(shell id -g $(USER)) \
                $(OPENLANE_IMAGE_NAME) sh -c $(OPENLANE_BASIC_COMMAND);\
```
So, there are TWO COPIES of the openlane scripts when running a design using the Caravel Makefile. One in /openlane and one in /openLANE_flow. The one that ships with the docker image is used according to the command line:
OPENLANE_BASIC_COMMAND = "cd /project/openlane && flow.tcl -design ./$* -save_path .. -save -tag $* -overwrite"
but that is a mistake!

### CODE REVIEW

**Comment by mguthaus** [comment]
Actually, this is a bigger issue. The script uses /project/openlane which refers to the relative copy "../openlane" due to this mount:
`-v $(PWD)/..:/project`
That means it will IGNORE $OPENLANE_ROOT entirely.

**Comment by mguthaus** [comment]
Reopening. This is the correct fix to update the mount point.

**Review by donn — APPROVED** [review]
From the OpenLane team- this was updated on our side. I can only assume it was just not reflected here. I recommend that this be merged.

**Comment by mguthaus** [comment]
Can we get a merge? It is still not right in the caravel and caravel-lite repos. @mkkassem @jeffdi @Manarabdelaty

**Pull request closed without merging**
